### ISSUE TITLE
Not playing back recorded strokes

### ISSUE THREAD

**Issue by parkerlreed** [werzum/MacroRecorder#1]
Tested pressing Super key ten times. It "registers" the presses but fails to play back.

Other keys don't seem to print anything to the terminal.

Arch Linux
python-pynput 1.7.7-1
python 3.12.6-1

```
[parker@parker-framework MacroRecorder]$ python macro_gui.py 
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Key.cmd press
Key.cmd release
Exception in thread Thread-2 (play_recorded_script):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/parker/build/MacroRecorder/macro_recorder.py", line 186, in play_recorded_script
    resolved_key = resolve_key(key_name)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/parker/build/MacroRecorder/macro_recorder.py", line 37, in resolve_key
    raise ValueError(f"Unknown key: {key_name}")
ValueError: Unknown key: Key.cmd

```

**Comment by werzum** [comment]
[This commit](https://github.com/werzum/MacroRecorder/commit/b28266b866b2c7340d2968c289341c42150d8fe3) should fix this - I manually added the special keys to a dictionary, which are looked up when playing the keystrokes. Pynput has the option to parse single chars from strings, but not special keys, and I didnt find any other option to create the Key.special_key objects other than manually looking them up. Maybe someone else has a better idea how to do that manually, but that should work for now - though of course some actual parsing instead of this hardcoded list would be much more elegant.
